export const ROLES = {
  AGENT: 'AGENT',
  TECHNICIEN: 'TECHNICIEN',
  RESPONSABLE: 'RESPONSABLE',
};

export const STATUT_DEMANDE = {
  EN_ATTENTE: 'EN_ATTENTE',
  VALIDEE: 'VALIDEE',
  EN_COURS: 'EN_COURS',
  RESOLUE: 'RESOLUE',
  REJETEE: 'REJETEE',
};

export const STATUT_COMPTE = {
  EN_ATTENTE: 'EN_ATTENTE',
  ACTIF: 'ACTIF',
  REJETE: 'REJETE',
};